export const INITIAL_COLLECTIONS_DATA = {
  base: {
    title: 'DevOps & Серверы',
    title_uz: 'DevOps & Serverlar',
    subtitle: 'Linux, Docker, Nginx, Git',
    subtitle_uz: 'Linux, Docker, Nginx, Git',
    desc: 'Базовые шпаргалки по Linux командам, Docker, Nginx, Git и SSH туннелям',
    desc_uz: "Linux buyruqlari, Docker, Nginx, Git va SSH bo'yicha asosiy shpargalkalar",
    color: '#38BDF8',
    icon: 'terminal',
    badge: 'DEVOPS',
    extra: 'Linux & Серверы',
    extra_uz: 'Linux & Serverlar',
    items: [
      { id: '1', title: 'Завершить процесс на порту 8080', title_uz: "8080 portidagi jarayonni to'xtatish", desc: 'Мгновенно находит и принудительно завершает любой зависший процесс, слушающий данный порт.', desc_uz: "Ko'rsatilgan portda ishlayotgan har qanday osilib qolgan jarayonni darhol to'xtatadi.", code: 'sudo fuser -k 8080/tcp', snippet: 'sudo fuser -k 8080/tcp', tag: 'Linux', tag_uz: 'Linux', type: 'command' },
      { id: '2', title: 'Логи ошибок в реальном времени', title_uz: 'Haqiqiy vaqtdagi xatolar jurnali', desc: 'Потоковый вывод только критических ошибок системного сервиса systemd без лишнего шума.', desc_uz: "Tizim servisidagi faqat xatoliklarni (err) real vaqt rejimida kuzatish.", code: 'journalctl -u my_app -f -p err', snippet: 'journalctl -u my_app -f -p err', tag: 'Linux', tag_uz: 'Linux', type: 'command' },
      { id: '3', title: 'Шаблон Reverse Proxy (Nginx)', title_uz: 'Reverse Proxy andozasi (Nginx)', desc: 'Проксирование входящих запросов на Node.js сервис с передачей реального IP клиента.', desc_uz: "Mijozning haqiqiy IP manzilini saqlagan holda so'rovlarni Node.js ga yo'naltirish.", code: 'location /api/ {\n  proxy_pass http://localhost:3000/;\n  proxy_set_header Host $host;\n  proxy_set_header X-Real-IP $remote_addr;\n}', snippet: 'location /api/ {\n  proxy_pass http://localhost:3000/;\n  proxy_set_header Host $host;\n  proxy_set_header X-Real-IP $remote_addr;\n}', tag: 'Nginx', tag_uz: 'Nginx', type: 'command' },
      { id: '4', title: 'Проверка конфигурации Nginx', title_uz: 'Nginx konfiguratsiyasini tekshirish', desc: 'Валидация синтаксиса конфига перед перезапуском, чтобы веб-сервер не упал при ошибке.', desc_uz: "Nginx-ni qayta ishga tushirishdan oldin xatoliklarga tekshirish va xavfsiz yangilash.", code: 'sudo nginx -t && sudo systemctl reload nginx', snippet: 'sudo nginx -t && sudo systemctl reload nginx', tag: 'Nginx', tag_uz: 'Nginx', type: 'command' },
      { id: '5', title: 'Очистить неиспользуемый Docker кэш', title_uz: "Foydalanilmayotgan Docker keshini tozalash", desc: 'Освобождает десятки гигабайт диска, удаляя зависшие контейнеры, слои и тома.', desc_uz: "Foydalanilmayotgan konteyner, image va disklarni o'chirib, gigabaytlab joy bo'shatadi.", code: 'docker system prune -a --volumes -f', snippet: 'docker system prune -a --volumes -f', tag: 'Docker', tag_uz: 'Docker', type: 'command' },
      { id: '6', title: 'Отменить последний Git коммит', title_uz: "Oxirgi Git commit-ni bekor qilish", desc: 'Мягкий откат коммита (soft reset): изменения сохраняются в индексе и не пропадают.', desc_uz: "Commit-ni bekor qiladi, lekin barcha o'zgarishlarni staging hududida saqlab qoladi.", code: 'git reset --soft HEAD~1', snippet: 'git reset --soft HEAD~1', tag: 'Git', tag_uz: 'Git', type: 'command' },
      { id: '7', title: 'Временно спрятать изменения (Stash)', title_uz: "O'zgarishlarni vaqtincha saqlash (Stash)", desc: 'Сохранение незавершенной работы в карман Git и возврат к ней после переключения веток.', desc_uz: "Tugallanmagan ishlarni vaqtincha yashirib, boshqa branchga o'tish va qaytib tiklash.", code: 'git stash save "wip" && git stash pop', snippet: 'git stash save "wip" && git stash pop', tag: 'Git', tag_uz: 'Git', type: 'command' },
      { id: '8', title: 'Топ 10 самых тяжелых директорий', title_uz: "Eng ko'p joy egallagan 10 ta jild", desc: 'Быстрый поиск виновников забитого диска в Linux с сортировкой по реальному размеру.', desc_uz: "Linux-da diskni to'ldirib yuborgan eng katta 10 ta papkani topish va saralash.", code: 'du -ah /var/log 2>/dev/null | sort -rh | head -n 10', snippet: 'du -ah /var/log 2>/dev/null | sort -rh | head -n 10', tag: 'Linux', tag_uz: 'Linux', type: 'command' },
      { id: '9', title: 'Замер времени ответа API (Curl)', title_uz: "API javob berish tezligini o'lchash (Curl)", desc: 'Точный замер длительности сетевого запроса к серверу без вывода тела ответа.', desc_uz: "Server javob tezligini (DNS, TCP, Total) terminalda soniyalarda aniq o'lchash.", code: 'curl -o /dev/null -s -w "Total time: %{time_total}s\\n" https://api.example.com/health', snippet: 'curl -o /dev/null -s -w "Total time: %{time_total}s\\n" https://api.example.com/health', tag: 'Network', tag_uz: 'Tarmoq', type: 'command' },
      { id: '10', title: 'Включение Gzip сжатия в Nginx', title_uz: 'Nginx-da Gzip siqishni yoqish', desc: 'Сжимает текстовые ответы, JS и JSON до 70%, существенно ускоряя загрузку сайта.', desc_uz: "Sayt tezligini oshirish uchun JSON, CSS va JS fayllarni serverda siqib yuborish.", code: 'gzip on;\ngzip_comp_level 5;\ngzip_types text/plain application/json application/javascript text/css;', snippet: 'gzip on;\ngzip_comp_level 5;\ngzip_types text/plain application/json application/javascript text/css;', tag: 'Nginx', tag_uz: 'Nginx', type: 'command' },
      { id: '11', title: 'Безопасный SSH туннель локального порта', title_uz: 'Xavfsiz SSH port tunnelini ochish', desc: 'Проброс удаленной защищенной БД (PostgreSQL) на localhost без открытия публичных портов.', desc_uz: "Masofaviy bazani (masalan Postgres) xavfsiz SSH orqali lokal portga bog'lash.", code: 'ssh -N -L 5432:localhost:5432 deploy@remote-server.com', snippet: 'ssh -N -L 5432:localhost:5432 deploy@remote-server.com', tag: 'DevOps', tag_uz: 'DevOps', type: 'command' },
      { id: '12', title: 'Список слушающих портов и процессов', title_uz: "Tinglayotgan portlar va jarayonlar ro'yxati", desc: 'Показывает все активные TCP порты сервера с именами процессов и их PID.', desc_uz: "Serverda hozir qaysi portlar ochiq va qaysi jarayonlar ishlayotganini ko'rish.", code: 'ss -tulpn | grep LISTEN', snippet: 'ss -tulpn | grep LISTEN', tag: 'Linux', tag_uz: 'Linux', type: 'command' },
    ]
  },
  courses: {
    title: 'Web & Backend Стек',
    title_uz: 'Web & Bekend Stek',
    subtitle: 'React, TS, Node, NestJS',
    subtitle_uz: 'React, TS, Node, NestJS',
    desc: 'React, React Native, TypeScript, Node.js & NestJS архитектура и тонкости рантайма',
    desc_uz: "React, React Native, TypeScript, Node.js va NestJS arxitekturasi va nozik jihatlari",
    color: '#FDE047',
    icon: 'code',
    badge: 'CORE',
    extra: 'Frontend & Бэкенд',
    extra_uz: 'Frontend & Bekend',
    items: [
      {
        id: '1',
        title: 'useMemo против useCallback',
        title_uz: 'useMemo yoki useCallback',
        desc: 'useMemo кэширует вычисленное значение (тяжелый расчет), а useCallback кэширует сам экземпляр функции между рендерами для дочерних компонентов.',
        desc_uz: "useMemo og'ir hisoblash natijasini keshlaydi, useCallback esa bolalar komponentlariga uzatiladigan funksiya havolasini keshlaydi.",
        code: '// useMemo: кэширует результат тяжелых вычислений\nconst memoizedValue = useMemo(() => computeHeavyData(items), [items]);\n\n// useCallback: кэширует ссылку на функцию для дочерних компонентов\nconst handleClick = useCallback(() => doSomething(id), [id]);',
        snippet: 'const memoizedValue = useMemo(() => computeHeavyData(items), [items]);',
        tag: 'React',
        tag_uz: 'React',
        type: 'code',
      },
      {
        id: '2',
        title: 'Автоматический Batching в React 18+',
        title_uz: 'React 18+ da avtomatik batching',
        desc: 'Все вызовы setState (даже внутри setTimeout, Promise и событий) объединяются в один рендер, исключая повторные перерисовки UI.',
        desc_uz: "Barcha setState chaqiruvlari (hatto setTimeout va Promise ichida ham) bitta renderga birlashadi va faqat 1 marta qayta chiziladi.",
        code: '// В React 18+ оба вызова setState объединятся в 1 общий рендер:\nsetTimeout(() => {\n  setCount(c => c + 1);\n  setFlag(f => !f); // 1 рендер вместо двух!\n}, 1000);',
        snippet: 'setTimeout(() => { setCount(c => c + 1); setFlag(f => !f); }, 1000);',
        tag: 'React',
        tag_uz: 'React',
        type: 'code',
      },
      {
        id: '3',
        title: 'Event Loop: фаза process.nextTick',
        title_uz: 'Event Loop: process.nextTick fazasi',
        desc: 'Выполняется сразу в Microtask очереди перед фазой таймеров (setImmediate и setTimeout) и имеет приоритет над Promise.',
        desc_uz: "Taymerlar fazasidan (setImmediate va setTimeout) oldin darhol Microtask navbatida Promise-dan ham tezroq bajariladi.",
        code: 'process.nextTick(() => console.log("1. nextTick (приоритетная микротаска)"));\nPromise.resolve().then(() => console.log("2. Promise микротаска"));\nsetTimeout(() => console.log("3. Таймер макротаска"), 0);',
        snippet: 'process.nextTick(() => console.log("nextTick"));',
        tag: 'Node',
        tag_uz: 'Node',
        type: 'code',
      },
      {
        id: '4',
        title: 'NestJS Singleton Scope по умолчанию',
        title_uz: 'NestJS Singleton ko\'lami',
        desc: 'Провайдеры (@Injectable) по умолчанию создаются как Singleton на всё приложение и кэшируются IoC контейнером.',
        desc_uz: "NestJS provayderlari (@Injectable) standart bo'yicha butun ilovada Singleton sifatida ishlaydi va qayta yaratilmaydi.",
        code: '@Injectable({ scope: Scope.DEFAULT })\nexport class CacheService {\n  private store = new Map<string, any>();\n  // Экземпляр один на всё приложение\n}',
        snippet: '@Injectable({ scope: Scope.DEFAULT }) export class CacheService {}',
        tag: 'Nest',
        tag_uz: 'Nest',
        type: 'code',
      },
      {
        id: '5',
        title: 'TypeScript: Utility Type ReturnType',
        title_uz: 'TypeScript: ReturnType utility turi',
        desc: 'Автоматически извлекает точный возвращаемый тип функции без ручного дублирования интерфейсов.',
        desc_uz: "Funksiya qaytaradigan turni interfeyslarni qo'lda takrorlamasdan avtomatik ajratib oladi.",
        code: 'type UserData = ReturnType<typeof fetchUserProfile>;\n// Автоматически получает тип, возвращаемый функцией fetchUserProfile',
        snippet: 'type UserData = ReturnType<typeof fetchUserProfile>;',
        tag: 'TypeScript',
        tag_uz: 'TypeScript',
        type: 'code',
      },
      {
        id: '6',
        title: 'TypeScript: Оператор satisfies',
        title_uz: 'TypeScript: satisfies operatori',
        desc: 'Проверяет соответствие типу без потери конкретных литеральных типов свойств (в отличие от обычного as Type).',
        desc_uz: "Turga mosligini tekshiradi, lekin as Type kabi literal turlarni yo'qotmaydi.",
        code: 'const theme = {\n  primary: "#FFD02F",\n  secondary: "#000000"\n} satisfies Record<string, string>;',
        snippet: 'const theme = { primary: "#FFD02F" } satisfies Record<string, string>;',
        tag: 'TypeScript',
        tag_uz: 'TypeScript',
        type: 'code',
      },
      {
        id: '7',
        title: 'React: Очистка асинхронных эффектов',
        title_uz: 'React: Asinxron effektlarni tozalash',
        desc: 'Флаг active защищает от race condition и утечек памяти при размонтировании компонента.',
        desc_uz: "Komponent ekrandan o'chirilganda xotira sizib chiqishi va Race Condition-dan himoya qiladi.",
        code: 'useEffect(() => {\n  let active = true;\n  fetchData().then(data => active && setState(data));\n  return () => { active = false; };\n}, [id]);',
        snippet: 'useEffect(() => {\n  let active = true;\n  fetchData().then(data => active && setState(data));\n  return () => { active = false; };\n}, [id]);',
        tag: 'React',
        tag_uz: 'React',
        type: 'code',
      },
      {
        id: '8',
        title: 'React Native: Оптимизация FlatList',
        title_uz: 'React Native: FlatList optimallashtirish',
        desc: 'Ключевые пропсы для устранения лагов и экономии оперативной памяти на длинных списках.',
        desc_uz: "Uzun ro'yxatlarda qotishlarni bartaraf etish va RAM tejash uchun muhim proplar.",
        code: '<FlatList\n  data={items}\n  initialNumToRender={10}\n  maxToRenderPerBatch={8}\n  windowSize={5}\n  removeClippedSubviews={true}\n  keyExtractor={(item) => item.id}\n/>',
        snippet: '<FlatList\n  initialNumToRender={10}\n  maxToRenderPerBatch={8}\n  windowSize={5}\n  removeClippedSubviews={true}\n/>',
        tag: 'RN',
        tag_uz: 'RN',
        type: 'code',
      },
      {
        id: '9',
        title: 'NestJS: Кастомный Param Decorator',
        title_uz: 'NestJS: Maxsus Param Decorator',
        desc: 'Извлекает авторизованного пользователя из HTTP-запроса прямо в параметры метода контроллера.',
        desc_uz: "Avtorizatsiyadan o'tgan foydalanuvchini to'g'ridan-to'g'ri kontroller metodiga parametr qilib uzatadi.",
        code: 'export const CurrentUser = createParamDecorator(\n  (data: unknown, ctx: ExecutionContext) => ctx.switchToHttp().getRequest().user\n);',
        snippet: 'export const CurrentUser = createParamDecorator(\n  (data: unknown, ctx: ExecutionContext) => ctx.switchToHttp().getRequest().user\n);',
        tag: 'Nest',
        tag_uz: 'Nest',
        type: 'code',
      },
      {
        id: '10',
        title: 'Node.js: Стриминг больших файлов (Streams)',
        title_uz: 'Node.js: Katta fayllarni oqimli uzatish (Streams)',
        desc: 'Передача гигабайтных файлов клиенту через Readable stream без расхода оперативной памяти сервера.',
        desc_uz: "Katta fayllarni butunlay RAM-ga yuklamasdan, oqimli (Stream) tarzda mijozga uzatish.",
        code: 'const stream = fs.createReadStream("huge_dataset.csv");\nstream.pipe(res); // отправка потоком без нагрузки на RAM',
        snippet: 'const stream = fs.createReadStream("huge_dataset.csv");\nstream.pipe(res);',
        tag: 'Node',
        tag_uz: 'Node',
        type: 'code',
      },
      {
        id: '11',
        title: 'Node.js: Worker Threads для CPU задач',
        title_uz: 'Node.js: CPU vazifalar uchun Worker Threads',
        desc: 'Выносит тяжелые математические расчеты и обработку медиа в отдельный системный поток, не блокируя Event Loop.',
        desc_uz: "Og'ir hisob-kitoblar va vazifalarni alohida tizim oqimiga chiqarib, Event Loop-ni bloklamaydi.",
        code: 'const { Worker, isMainThread } = require("worker_threads");\nif (isMainThread) {\n  const worker = new Worker("./heavy-calc.js");\n  worker.on("message", (result) => console.log("Готово:", result));\n}',
        snippet: 'const { Worker, isMainThread } = require("worker_threads");',
        tag: 'Node',
        tag_uz: 'Node',
        type: 'code',
      },
      {
        id: '12',
        title: 'NestJS: Глобальный Exception Filter',
        title_uz: 'NestJS: Global Exception Filter',
        desc: 'Централизованный перехват и унификация всех необработанных исключений в единый JSON формат ответа.',
        desc_uz: "Barcha kutilmagan xatoliklarni bitta joyda ushlab, yagona JSON formatida javob qaytarish.",
        code: '@Catch()\nexport class AllExceptionsFilter implements ExceptionFilter {\n  catch(exception: unknown, host: ArgumentsHost) {\n    const ctx = host.switchToHttp();\n    ctx.getResponse().status(500).json({ error: "Internal Error" });\n  }\n}',
        snippet: '@Catch()\nexport class AllExceptionsFilter implements ExceptionFilter {\n  catch(exception: unknown, host: ArgumentsHost) { ... }\n}',
        tag: 'Nest',
        tag_uz: 'Nest',
        type: 'code',
      },
    ]
  },
  chill: {
    title: 'Разбор Интервью',
    title_uz: 'Intervyu Savollari',
    subtitle: 'Closure, EventLoop, SQL',
    subtitle_uz: 'Closure, EventLoop, SQL',
    desc: 'Каверзные вопросы и нюансы с технических собеседований на Middle / Senior',
    desc_uz: 'Middle / Senior darajadagi texnik intervyulardagi qiyin savollar va nozik nuqtalar',
    color: '#84CC16',
    icon: 'award',
    badge: 'INTERVIEW',
    extra: 'Интервью & Задачи',
    extra_uz: 'Intervyu & Masalalar',
    items: [
      {
        id: '1',
        title: 'Замыкание (Closure) простыми словами',
        title_uz: 'Yopilishlar (Closure) oddiy tilda',
        desc: 'Функция запоминает переменные из своей внешней лексической области видимости даже после того, как внешняя функция завершила работу.',
        desc_uz: "Funksiya tashqi funksiya bajarilib bo'lgandan keyin ham tashqi o'zgaruvchilarni leksik muhitda eslab qoladi.",
        code: 'function createCounter() {\n  let count = 0;\n  return () => ++count; // хранит доступ к count в замыкании\n}\nconst counter = createCounter();\ncounter(); // 1\ncounter(); // 2',
        snippet: 'function createCounter() { let count = 0; return () => ++count; }',
        tag: 'JS',
        tag_uz: 'JS',
        type: 'code',
      },
      {
        id: '2',
        title: 'Почему 0.1 + 0.2 !== 0.3?',
        title_uz: 'Nima uchun 0.1 + 0.2 !== 0.3?',
        desc: 'Числа в JS хранятся в 64-битном стандарте IEEE 754. В двоичной системе 0.1 и 0.2 дают бесконечные периодические дроби, из-за чего возникает микропогрешность 0.30000000000000004.',
        desc_uz: "IEEE 754 standarti ikkilik tizimda 0.1 va 0.2 ni aniq ifodalay olmaydi, natijada 0.30000000000000004 hosil bo'ladi.",
        code: 'console.log(0.1 + 0.2); // 0.30000000000000004\n\n// Надежное сравнение с машинным эпсилоном:\nconst isEqual = Math.abs((0.1 + 0.2) - 0.3) < Number.EPSILON; // true',
        snippet: 'const isEqual = Math.abs((0.1 + 0.2) - 0.3) < Number.EPSILON;',
        tag: 'JS',
        tag_uz: 'JS',
        type: 'code',
      },
      {
        id: '3',
        title: 'Подвох Error Middleware в Express',
        title_uz: 'Express-da Error Middleware nozikligi',
        desc: 'Express определяет Error Middleware строго по количеству аргументов функции (fn.length === 4). Если опустить параметр next, Express посчитает обработчик обычным роутом!',
        desc_uz: "Aynan 4 ta argument qabul qilishi shart: (err, req, res, next), aks holda Express uni oddiy handler deb hisoblaydi.",
        code: '// Обязательно ровно 4 параметра: (err, req, res, next)\napp.use((err, req, res, next) => {\n  console.error(err.stack);\n  res.status(500).json({ error: err.message });\n});',
        snippet: 'app.use((err, req, res, next) => { res.status(500).json({ error: err.message }); });',
        tag: 'Express',
        tag_uz: 'Express',
        type: 'code',
      },
      {
        id: '4',
        title: 'Каверзный кейс: [] == ![]',
        title_uz: 'Qiziqarli holat: [] == ![]',
        desc: 'Шаги неявного приведения типов: 1) ![] дает false. 2) [] == false -> [] приводится к строке "". 3) "" == false -> оба приводятся к числу 0 == 0 -> true!',
        desc_uz: "![] qiymati false bo'ladi. So'ng [] bo'sh satrga \"\", keyin 0 ga aylanadi: 0 == 0 -> true!",
        code: 'console.log([] == ![]);  // true  (неявная коэрциция типов)\nconsole.log([] === ![]); // false (object !== boolean)',
        snippet: 'console.log([] == ![]); // true',
        tag: 'JS',
        tag_uz: 'JS',
        type: 'code',
      },
      {
        id: '5',
        title: 'Всплытие и TDZ (Temporal Dead Zone)',
        title_uz: 'Ko\'tarilish (Hoisting) va TDZ',
        desc: 'Переменные let и const всплывают (hoisted), но не инициализируются значением undefined (как var). Обращение к ним до строки объявления выбрасывает ReferenceError.',
        desc_uz: "let/const o'zgaruvchilari e'lon qilinmaguncha TDZ hududida bo'ladi va murojaat ReferenceError beradi.",
        code: '// console.log(x); // ReferenceError: Cannot access "x" before initialization\nlet x = 42;\nconsole.log(x); // 42',
        snippet: 'let x = 42; // До этой строки переменная находится в TDZ',
        tag: 'JS',
        tag_uz: 'JS',
        type: 'code',
      },
      {
        id: '6',
        title: 'Microtasks против Macrotasks',
        title_uz: 'Microtask va Macrotask farqi',
        desc: 'Очередь Microtasks (Promise, process.nextTick, queueMicrotask) имеет наивысший приоритет и очищается целиком после КАЖДОЙ макротаски (setTimeout, I/O).',
        desc_uz: "Microtasklar (Promise, queueMicrotask) barcha macrotasklardan (setTimeout, I/O) OLDIN to'liq bajariladi.",
        code: 'setTimeout(() => console.log("1. Macro: setTimeout"), 0);\nPromise.resolve().then(() => console.log("2. Micro: Promise"));\n// Порядок в консоли: 2 (Micro), затем 1 (Macro)',
        snippet: 'setTimeout(() => console.log("Macro"), 0); Promise.resolve().then(() => console.log("Micro"));',
        tag: 'EventLoop',
        tag_uz: 'EventLoop',
        type: 'code',
      },
      {
        id: '7',
        title: 'Нативное глубокое копирование объектов',
        title_uz: 'Obyektlarni chuqur nusxalash',
        desc: 'Современный платформенный метод глубокого клонирования сложных объектов, циклических ссылок, Set, Map и Date без хаков с JSON.parse.',
        desc_uz: "JSON.parse ishlatmasdan zamonaviy, tezkor va Date/Set/Map-ni to'liq saqlagan holda chuqur klonlash.",
        code: 'const original = { user: { name: "Alisher" }, date: new Date() };\nconst clone = structuredClone(original);',
        snippet: 'const clone = structuredClone(originalObject);',
        tag: 'JS',
        tag_uz: 'JS',
        type: 'code',
      },
      {
        id: '8',
        title: 'Реализация Debounce на коленке',
        title_uz: 'Oddiy Debounce funksiyasi',
        desc: 'Откладывает вызов переданной функции до тех пор, пока не пройдет заданный таймаут бездействия (идеально для поиска и автосохранения).',
        desc_uz: "Foydalanuvchi yozishni to'xtatgandan keyin berilgan vaqt o'tib funksiyani ishga tushiradi (qidiruv uchun).",
        code: 'const debounce = (fn, ms = 300) => {\n  let timeoutId;\n  return (...args) => {\n    clearTimeout(timeoutId);\n    timeoutId = setTimeout(() => fn(...args), ms);\n  };\n};',
        snippet: 'const debounce = (fn, ms) => { let t; return (...a) => { clearTimeout(t); t = setTimeout(() => fn(...a), ms); }; };',
        tag: 'JS',
        tag_uz: 'JS',
        type: 'code',
      },
      {
        id: '9',
        title: 'Сложность поиска: Array vs Set',
        title_uz: 'Qidirish murakkabligi: Array vs Set',
        desc: 'В обычном массиве поиск includes(val) выполняется за линейное время O(n). В хэш-таблицах Set и Map поиск по значению происходит за мгновенное O(1).',
        desc_uz: "Massivda array.includes(val) O(n) vaqt oladi, set.has(val) esa doimiy O(1) vaqtda topadi.",
        code: 'const set = new Set(largeArray);\nset.has("targetKey"); // O(1) константная скорость поиска даже на 1 000 000 элементов',
        snippet: 'const set = new Set(largeArray); set.has(val); // O(1)',
        tag: 'Big-O',
        tag_uz: 'Big-O',
        type: 'code',
      },
      {
        id: '10',
        title: 'SQL: В чём разница WHERE и HAVING?',
        title_uz: 'SQL: WHERE va HAVING farqi nimada?',
        desc: 'WHERE отсекает отдельные строки ДО группировки GROUP BY. HAVING фильтрует уже сгруппированные данные ПОСЛЕ выполнения агрегатных функций (COUNT, SUM, AVG).',
        desc_uz: "WHERE satrlarni GROUP BY-dan OLDIN filtrlaydi, HAVING esa jamlangan ma'lumotlarni KEYIN filtrlaydi.",
        code: 'SELECT department, COUNT(*) AS devs\nFROM employees\nWHERE is_active = true -- фильтр ДО группировки\nGROUP BY department\nHAVING COUNT(*) >= 5;  -- фильтр ПОСЛЕ агрегации',
        snippet: 'SELECT department, COUNT(*) FROM employees WHERE is_active = true GROUP BY department HAVING COUNT(*) >= 5;',
        tag: 'SQL',
        tag_uz: 'SQL',
        type: 'code',
      },
      {
        id: '11',
        title: 'WeakMap против обычного Map в JS',
        title_uz: 'JS-da WeakMap va Map farqi',
        desc: 'В WeakMap ключами могут быть ТОЛЬКО объекты, и ссылки на них «слабые». Если на объект-ключ больше нет других ссылок в программе, Garbage Collector очистит его из памяти.',
        desc_uz: "WeakMap-da kalitlar FAQAT obyekt bo'lishi mumkin va xotira tozalagichga (GC) xalaqit bermaydi.",
        code: 'let user = { id: 1 };\nconst metadata = new WeakMap();\nmetadata.set(user, { role: "admin" });\nuser = null; // GC автоматически удалит запись из WeakMap',
        snippet: 'const wm = new WeakMap(); wm.set(obj, data);',
        tag: 'JS',
        tag_uz: 'JS',
        type: 'code',
      },
      {
        id: '12',
        title: 'Почему typeof null === "object"?',
        title_uz: 'Nega typeof null === "object"?',
        desc: 'Исторический баг первой реализации JavaScript (1995 г.): типы кодировались 32-битными дескрипторами. Метка 000 означала объект, а null представлялся нулевым указателем (все нули).',
        desc_uz: "JS-ning birinchi versiyasidagi tarixiy xatolik: null kodi 000 bo'lib, u obyekt tegi bilan mos tushib qolgan.",
        code: 'typeof null; // "object" (исторический артефакт JS)\n\n// Надежная проверка на null:\nconst isNull = (val) => val === null;',
        snippet: 'typeof null === "object"; // bug in JS since 1995',
        tag: 'JS',
        tag_uz: 'JS',
        type: 'code',
      },
    ]
  },
  roadmap: {
    title: 'Архитектура & БД',
    title_uz: 'Arxitektura & MB',
    subtitle: 'System Design, SQL, Redis',
    subtitle_uz: 'System Design, SQL, Redis',
    desc: 'Системный дизайн, отказоустойчивость, базы данных, паттерны и микросервисы',
    desc_uz: "Tizim dizayni, ishonchlilik, ma'lumotlar bazasi va mikroxizmatlar",
    color: '#FB7185',
    icon: 'layers',
    badge: 'DESIGN',
    extra: 'Архитектура & БД',
    extra_uz: 'Arxitektura & MB',
    items: [
      {
        id: '1',
        title: 'Бэкенд Roadmap 2026',
        title_uz: 'Bekend yo\'l xaritasi 2026',
        desc: 'Ключевые технологические этапы роста бэкенд-инженера от монолита к highload-системам:',
        desc_uz: "Monolitdan yuqori yuklamali tizimlargacha bo'lgan bekend muhandisining asosiy yo'nalishlari:",
        points: [
          'Node.js & TypeScript — надежная асинхронность и строгая типизация',
          'PostgreSQL & Redis — реляционные данные и мгновенный кэш',
          'Docker & CI/CD — контейнеризация и автоматизация деплоя',
          'Kubernetes & Kafka — оркестрация и событийно-ориентированный стриминг',
          'Grafana & Prometheus — мониторинг метрик и трейсинг запросов',
        ],
        points_uz: [
          "Node.js & TypeScript — kuchli asinxronlik va qat'iy turlanish",
          "PostgreSQL & Redis — relyatsion ma'lumotlar va tezkor kesh",
          "Docker & CI/CD — konteynerlar va avtomatlashtirilgan deploy",
          "Kubernetes & Kafka — mikroxizmatlar va hodisalarga asoslangan oqim",
          "Grafana & Prometheus — metrikalar monitoringi va tracing",
        ],
        tag: 'Roadmap',
        tag_uz: 'Reja',
        type: 'concept',
      },
      {
        id: '2',
        title: 'Паттерн Graceful Shutdown',
        title_uz: 'Graceful Shutdown andozasi',
        desc: 'Корректная остановка сервера: завершает текущие HTTP-запросы, закрывает сокеты и соединения с БД без потери данных клиентов.',
        desc_uz: "Serverni xavfsiz to'xtatish: joriy HTTP so'rovlarni yakunlaydi, MB va Redis ulanishlarini xavfsiz yopadi.",
        code: 'process.on("SIGTERM", async () => {\n  console.log("SIGTERM получен, закрываем сервер...");\n  server.close(async () => {\n    await db.$disconnect();\n    await redis.quit();\n    process.exit(0);\n  });\n});',
        snippet: 'process.on("SIGTERM", async () => { server.close(); });',
        tag: 'Архитектура',
        tag_uz: 'Arxitektura',
        type: 'code',
      },
      {
        id: '3',
        title: 'Золотое правило индексов БД',
        title_uz: 'MB indekslarining oltin qoidasi',
        desc: 'Индексируйте колонки в WHERE, JOIN и ORDER BY с высокой кардинальностью (уникальностью значений). Не создавайте избыточные индексы на таблицы с частой записью, так как каждый INSERT/UPDATE перестраивает индексное B-Tree.',
        desc_uz: "WHERE, JOIN va ORDER BY-da ko'p qatnashadigan ustunlarga indeks qo'ying. Lekin tez-tez yoziladigan jadvallarga ortiqcha indeks bermang, chunki INSERT/UPDATE sekinlashadi.",
        tag: 'Database',
        tag_uz: 'MB',
        type: 'concept',
      },
      {
        id: '4',
        title: 'Паттерн Idempotency Key в платежах',
        title_uz: 'To\'lovlarda Idempotency Key andozasi',
        desc: 'Клиент передает уникальный заголовок Idempotency-Key (UUIDv4). Сервер атомарно сохраняет ключ в Redis на 24ч (SETNX). При повторных запросах из-за сбоев сети средства не списываются дважды, а отдается сохраненный результат.',
        desc_uz: "Mijoz takrorlanmas Idempotency-Key (UUID) yuboradi. Server uni Redis-da tekshirib, internet uzilib qayta so'rov yuborilganda mablag' ikki marta yechilishini 100% oldini oladi.",
        tag: 'API Design',
        tag_uz: 'API',
        type: 'concept',
      },
      {
        id: '5',
        title: 'Паттерн Circuit Breaker (Предохранитель)',
        title_uz: 'Circuit Breaker (Saqlagich) andozasi',
        desc: 'Предотвращает каскадное падение микросервисов. Если внешний сервис выдает ошибки N раз подряд, «рубильник» размыкается (Open), мгновенно отдавая fallback-ответ без траты времени на зависшие таймауты.',
        desc_uz: "Tizimni kaskadli qulashdan asraydi. Agar tashqi servis ketma-ket N marta xato bersa, so'rovlar vaqtincha to'xtatilib, darhol zaxira fallback javob qaytariladi.",
        tag: 'Архитектура',
        tag_uz: 'Arxitektura',
        type: 'concept',
      },
      {
        id: '6',
        title: 'Репликация БД: Master-Slave',
        title_uz: 'Ma\'lumotlar bazasi replikatsiyasi',
        desc: 'Главный сервер (Master) обрабатывает 100% операций записи (INSERT, UPDATE, DELETE). Несколько вторичных серверов (Slaves/Replicas) асинхронно копируют журнал транзакций (WAL) и горизонтально масштабируют чтение (SELECT).',
        desc_uz: "Master barcha yozish (INSERT/UPDATE) amallarini qabul qiladi. Bir nechta Slave replikalari esa faqat o'qish (SELECT) yuklamasini o'zaro taqsimlaydi.",
        tag: 'Database',
        tag_uz: 'MB',
        type: 'concept',
      },
      {
        id: '7',
        title: 'Паттерн CQRS (Разделение команд и запросов)',
        title_uz: 'CQRS andozasi',
        desc: 'Модели для изменения состояния (Commands) и модели для выборки (Queries) полностью разделяются. Это позволяет оптимизировать таблицы на запись (3NF) и независимо оптимизировать выборку под сложную витрину данных.',
        desc_uz: "Ma'lumotlarni o'zgartirish (Commands) va o'qish (Queries) modellari mustaqil optimallashtirish va alohida kesh/bazalar bilan ishlash uchun ajratiladi.",
        tag: 'Архитектура',
        tag_uz: 'Arxitektura',
        type: 'concept',
      },
      {
        id: '8',
        title: 'Очереди: Kafka против RabbitMQ',
        title_uz: 'Navbatlar: Kafka yoki RabbitMQ',
        desc: 'RabbitMQ — умный брокер очередей (push-модель, routing keys, сложная фильтрация, удаление сообщений после ack). Kafka — распределенный неизменяемый лог событий (pull-модель, партиционирование, миллионы сообщений/сек).',
        desc_uz: "RabbitMQ — aqlli navbat brokeri (push-model, xabarlar o'chiriladi). Kafka — taqsimlangan hodisalar jurnali (pull-model, xabarlar saqlanadi, o'ta tezkor).",
        tag: 'Brokers',
        tag_uz: 'Brokerlar',
        type: 'concept',
      },
      {
        id: '9',
        title: 'Rate Limiting: Token Bucket алгоритм',
        title_uz: 'Rate Limiting: Token Bucket algoritmi',
        desc: 'В виртуальное ведро емкостью N токенов каждую секунду добавляется R токенов. Запрос забирает токен; если ведро пусто — сервер мгновенно возвращает статус 429 Too Many Requests, защищая API от DDoS.',
        desc_uz: "Chelakka har soniyada token quyiladi. Har bir so'rov token sarflaydi; chelak bo'shab qolsa — server 429 Too Many Requests berib, DDoS-dan saqlaydi.",
        tag: 'Security',
        tag_uz: 'Xavfsizlik',
        type: 'concept',
      },
      {
        id: '10',
        title: 'Типы индексов PostgreSQL: B-Tree vs GIN',
        title_uz: 'PostgreSQL indekslari: B-Tree vs GIN',
        desc: 'B-Tree — универсален для числовых сравнений (=, <, >, BETWEEN). GIN (Generalized Inverted Index) незаменим для документов JSONB, тегов-массивов и полнотекстового поиска.',
        desc_uz: "B-Tree tenglik va oraliqlar uchun (=, <, >). GIN esa JSONB hujjatlar, massivlar va to'liq matnli qidiruv uchun eng tezkor indeksdir.",
        code: '-- GIN индекс для мгновенного поиска по JSONB и массивам тегов:\nCREATE INDEX idx_products_tags ON products USING GIN (tags);\nCREATE INDEX idx_users_meta ON users USING GIN (metadata jsonb_path_ops);',
        snippet: 'CREATE INDEX idx_tags ON items USING GIN (tags);',
        tag: 'Database',
        tag_uz: 'MB',
        type: 'code',
      },
      {
        id: '11',
        title: 'Кэширование: Паттерн Cache-Aside',
        title_uz: 'Keshlashtirish: Cache-Aside andozasi',
        desc: 'Сервис сначала проверяет кэш в Redis. При miss — запрашивает данные из БД, сохраняет их в Redis с TTL и отдает ответ клиенту.',
        desc_uz: "Ilova avval Redis-dan qidiradi. Topilmasa — bazadan olib, Redis-ga TTL bilan yozadi va mijozga qaytaradi.",
        code: 'let user = await redis.get(`user:${id}`);\nif (!user) {\n  user = await db.user.findUnique({ where: { id } });\n  await redis.set(`user:${id}`, JSON.stringify(user), "EX", 3600); // TTL 1 час\n}',
        snippet: 'let user = await redis.get(key); if (!user) { user = await db.get(); await redis.set(key, user); }',
        tag: 'Caching',
        tag_uz: 'Kesh',
        type: 'code',
      },
      {
        id: '12',
        title: 'Горизонтальное шардирование БД',
        title_uz: 'Ma\'lumotlar bazasini shardlash',
        desc: 'Разделение огромной таблицы на независимые серверы баз данных по ключу шардирования (например user_id % 4). Позволяет преодолеть аппаратные лимиты диска и CPU одного физического сервера.',
        desc_uz: "Gigant jadvalni shard kaliti (masalan user_id % 4) bo'yicha bir nechta alohida serverlarga taqsimlab, bitta server chegaralaridan chiqish.",
        tag: 'Scalability',
        tag_uz: 'Masshtab',
        type: 'concept',
      },
    ]
  },
  english: {
    title: 'IT Английский',
    title_uz: 'IT Ingliz tili',
    subtitle: 'Daily, Code Review, Slack',
    subtitle_uz: 'Daily, Code Review, Slack',
    desc: 'IT English: фразы для дейли, код-ревью, переговоров и архитектуры',
    desc_uz: 'IT Ingliz tili: daily, code review va muzokaralar uchun professional iboralar',
    color: '#A855F7',
    icon: 'globe',
    badge: 'ENGLISH',
    extra: 'IT Лексикон',
    extra_uz: 'IT Lug\'at',
    items: [
      {
        id: '1',
        title: 'Блокер на дейли (Blocker on daily)',
        title_uz: 'Dailydagi to\'siq (Blocker on daily)',
        phrase: 'I am currently blocked by the auth endpoint. Could we sync up after the standup?',
        desc: 'Как сообщить команде о препятствии в разработке и запросить быстрый созвон после митинга.',
        desc_uz: "Daily-da o'zingizni to'xtatib turgan muammo haqida aytish va mitingdan keyin qisqa sinxronlashuv so'rash.",
        snippet: 'I am currently blocked by the auth endpoint. Could we sync up after the standup?',
        tag: 'Фразы',
        tag_uz: 'Iboralar',
        type: 'phrase',
      },
      {
        id: '2',
        title: 'Отложить тему (To table a discussion)',
        title_uz: 'Mavzuni kechiktirish (To table a discussion)',
        phrase: "Let's table this discussion for the retro.",
        desc: 'Вежливый способ предложить не спорить прямо сейчас, а вынести обсуждение на ретроспективу.',
        desc_uz: "Hozir bahslashmasdan, mavzuni retrospektivaga olib chiqishni taklif qilish.",
        snippet: "Let's table this discussion for the retro.",
        tag: 'Идиомы',
        tag_uz: 'Idiomalar',
        type: 'phrase',
      },
      {
        id: '3',
        title: 'Нет времени / ресурса (No bandwidth)',
        title_uz: 'Vaqt/imkoniyat yo\'q (No bandwidth)',
        phrase: "I don't have the bandwidth to take on extra tickets this sprint.",
        desc: 'Профессиональный отказ брать новые тикеты, когда текущий спринт уже максимально загружен.',
        desc_uz: "Joriy sprintda qo'shimcha vazifalarni olishga vaqt va resurs yetarli emasligini tushuntirish.",
        snippet: "I don't have the bandwidth to take on extra tickets this sprint.",
        tag: 'Сленг',
        tag_uz: 'Sleng',
        type: 'phrase',
      },
      {
        id: '4',
        title: 'Инженерный компромисс (Trade-off)',
        title_uz: 'Murosaga kelish (Trade-off)',
        phrase: "It's an engineering trade-off between write throughput and query latency.",
        desc: 'Аргумент в архитектурном споре: баланс между скоростью записи и задержкой чтения.',
        desc_uz: "Arxitektura muhokamasida: yozish tezligi va o'qish kechikishi o'rtasidagi muhandislik murosasi.",
        snippet: "It's an engineering trade-off between write throughput and query latency.",
        tag: 'Архитектура',
        tag_uz: 'Arxitektura',
        type: 'phrase',
      },
      {
        id: '5',
        title: 'Замечание в PR без блокировки (Nitpick)',
        title_uz: 'PR-dagi kichik eslatma (Nitpick)',
        phrase: 'nit: consider extracting this helper function, non-blocking.',
        desc: 'Префикс "nit" означает мелкую придирку по кодстайлу, которая не блокирует аппрув и мердж пулл-реквеста.',
        desc_uz: '"nit" prefiksi kod uslubi bo\'yicha kichik taklif bo\'lib, PR-ni tasdiqlashga to\'sqinlik qilmaydi.',
        snippet: 'nit: consider extracting this helper function, non-blocking.',
        tag: 'Code Review',
        tag_uz: 'Code Review',
        type: 'phrase',
      },
      {
        id: '6',
        title: 'Одобрение PR (LGTM / Ship it)',
        title_uz: 'PR-ni tasdiqlash (LGTM / Ship it)',
        phrase: 'Looks good to me, test coverage is great. Ship it!',
        desc: 'Финальный аппрув изменений: код проверен, тесты написаны, можно катить релиз в прод.',
        desc_uz: "Yakuniy tasdiq: kod tekshirildi, testlar to'liq, relizni prod-ga chiqarish mumkin.",
        snippet: 'Looks good to me, test coverage is great. Ship it!',
        tag: 'Code Review',
        tag_uz: 'Code Review',
        type: 'phrase',
      },
      {
        id: '7',
        title: 'Сократить скоуп задачи (Push back on scope)',
        title_uz: 'Vazifa ko\'lamini qisqartirish (Push back)',
        phrase: 'We need to push back on the export feature to hit the Q3 release deadline.',
        desc: 'Как обосновать менеджменту необходимость урезать фичи ради соблюдения дедлайна.',
        desc_uz: "Belgilangan muddatga ulgurish uchun ayrim ikkinchi darajali funksiyalarni qisqartirishni taklif qilish.",
        snippet: 'We need to push back on the export feature to hit the Q3 release deadline.',
        tag: 'Менеджмент',
        tag_uz: 'Boshqaruv',
        type: 'phrase',
      },
      {
        id: '8',
        title: 'Вне рамок задачи (Out of scope)',
        title_uz: 'Vazifadan tashqari (Out of scope)',
        phrase: 'Real-time audio processing is out of scope for the current MVP milestone.',
        desc: 'Защита границ текущей задачи от расползания скоупа (scope creep) во время планирования.',
        desc_uz: "Ushbu imkoniyat joriy MVP vazifasiga kirmasligini va keyingi bosqichga qolishini ko'rsatish.",
        snippet: 'Real-time audio processing is out of scope for the current MVP milestone.',
        tag: 'Фразы',
        tag_uz: 'Iboralar',
        type: 'phrase',
      },
      {
        id: '9',
        title: 'Предупреждение / К сведению (Heads-up)',
        title_uz: 'Ogohlantirish / Diqqat (Heads-up)',
        phrase: 'Just a quick heads-up: production deployment is scheduled for 18:00 UTC.',
        desc: 'Короткое информационное уведомление для команды о скорых технических работах или деплое.',
        desc_uz: "Jamoaga tez orada bo'ladigan texnik ishlar yoki reliz haqida qisqa eslatma berish.",
        snippet: 'Just a quick heads-up: production deployment is scheduled for 18:00 UTC.',
        tag: 'Коммуникация',
        tag_uz: 'Muloqot',
        type: 'phrase',
      },
      {
        id: '10',
        title: 'Сверить часы / Созвониться (Touch base)',
        title_uz: 'Aloqaga chiqish / Kelishib olish (Touch base)',
        phrase: "Let's touch base tomorrow morning regarding the database migration plan.",
        desc: 'Предложение провести короткую синхронизацию по сложной задаче или плану миграции.',
        desc_uz: "Ertaga ertalab MB migratsiyasi rejasini birgalikda tekshirib olish uchun qisqa aloqaga chiqish.",
        snippet: "Let's touch base tomorrow morning regarding the database migration plan.",
        tag: 'Коммуникация',
        tag_uz: 'Muloqot',
        type: 'phrase',
      },
      {
        id: '11',
        title: 'Ввести в курс дела (Bring up to speed)',
        title_uz: 'Vaziyat bilan tanishtirish (Bring up to speed)',
        phrase: 'Could you bring me up to speed on the recent billing service refactoring?',
        desc: 'Вежливая просьба к коллеге кратко рассказать о контексте изменений в проекте.',
        desc_uz: "Hamkasbdan so'nggi arxitektura o'zgarishlari va billing xizmati yangiliklarini qisqacha tushuntirib berishini so'rash.",
        snippet: 'Could you bring me up to speed on the recent billing service refactoring?',
        tag: 'Фразы',
        tag_uz: 'Iboralar',
        type: 'phrase',
      },
      {
        id: '12',
        title: 'Остаться при своем мнении (Agree to disagree)',
        title_uz: 'O\'z fikrida qolish (Agree to disagree)',
        phrase: 'We can agree to disagree on the formatting and let the team linter decide.',
        desc: 'Конструктивное завершение непродуктивного спора: оппоненты соглашаются на автоматическое правило линтера.',
        desc_uz: "Foydasiz bahsni to'xtatish: har kim o'z fikrida qoladi va jamoa linteri qoidasiga amal qilinadi.",
        snippet: 'We can agree to disagree on the formatting and let the team linter decide.',
        tag: 'Дискуссии',
        tag_uz: 'Munozara',
        type: 'phrase',
      },
    ]
  },
  tools: {
    title: 'Тулзы & Утилиты',
    title_uz: 'Foydali vositalar',
    subtitle: 'Regex, Bundle, Crontab',
    subtitle_uz: 'Regex, Bundle, Crontab',
    desc: 'Незаменимые онлайн-сервисы, чеклисты и утилиты разработчика',
    desc_uz: 'Dasturchilar uchun eng zarur onlayn servislar va utilitalar',
    color: '#FB923C',
    icon: 'tool',
    badge: 'TOOLS',
    extra: 'Онлайн-сервисы',
    extra_uz: 'Onlayn servislar',
    items: [
      {
        id: '1',
        title: 'Regex101: Отладка регулярных выражений',
        title_uz: 'Regex101: Muntazam ifodalar tekshiruvi',
        url: 'https://regex101.com',
        desc: 'Интерактивный онлайн-тестер регулярных выражений с подробным пошаговым разбором токенов и тестами.',
        desc_uz: "Har qanday regexni tekshirish, sinash va bosqichma-bosqich tahlil qilish uchun eng zo'r onlayn asbob.",
        snippet: 'https://regex101.com',
        tag: 'Web',
        tag_uz: 'Web',
        type: 'tool',
      },
      {
        id: '2',
        title: 'Bundlephobia: Вес NPM пакетов',
        title_uz: 'Bundlephobia: NPM paketlar hajmi',
        url: 'https://bundlephobia.com',
        desc: 'Мгновенный замер размера npm-зависимости, времени загрузки на 3G/4G и влияния на итоговый бандл.',
        desc_uz: "Kutubxonani loyihaga o'rnatishdan oldin uning bundle hajmi va yuklanish tezligini bilib olish.",
        snippet: 'https://bundlephobia.com',
        tag: 'JS',
        tag_uz: 'JS',
        type: 'tool',
      },
      {
        id: '3',
        title: 'Crontab Guru: Калькулятор расписания cron',
        title_uz: 'Crontab Guru: Cron jadval hisoblagichi',
        url: 'https://crontab.guru',
        desc: 'Интерактивный визуализатор и валидатор cron-расписаний с подсказками по синтаксису и времени запуска.',
        desc_uz: "Cron formatini (* * * * *) inson tushunadigan vaqtga aylantiruvchi qulay kalkulyator.",
        snippet: 'https://crontab.guru',
        tag: 'DevOps',
        tag_uz: 'DevOps',
        type: 'tool',
      },
      {
        id: '4',
        title: 'JSON Crack: Визуализация сложных JSON деревьев',
        title_uz: 'JSON Crack: JSON tuzilmasini vizuallashtirish',
        url: 'https://jsoncrack.com',
        desc: 'Превращает огромные и вложенные JSON-объекты в наглядную интерактивную диаграмму-граф.',
        desc_uz: "Katta va murakkab JSON ma'lumotlarini chiroyli interaktiv daraxt ko'rinishida tasvirlash.",
        snippet: 'https://jsoncrack.com',
        tag: 'Tools',
        tag_uz: 'Vosita',
        type: 'tool',
      },
      {
        id: '5',
        title: 'Explain Shell: Разбор сложных bash команд',
        title_uz: 'Explain Shell: Bash buyruqlarini tushuntirish',
        url: 'https://explainshell.com',
        desc: 'Разбивает сложную bash/Linux команду на составляющие и выводит выдержку из man-страниц для каждого флага.',
        desc_uz: "Terminaldagi har qanday uzun buyruq va bayroqlarning rasmiy man-hujjatlardagi ma'nosini ko'rsatish.",
        snippet: 'https://explainshell.com',
        tag: 'Linux',
        tag_uz: 'Linux',
        type: 'tool',
      },
      {
        id: '6',
        title: 'Can I Use: Поддержка фичей браузерами',
        title_uz: 'Can I Use: Brauzerlar imkoniyatlari',
        url: 'https://caniuse.com',
        desc: 'База данных совместимости HTML5, CSS3 и JS API с браузерами (Chrome, Safari, Firefox, iOS, Android).',
        desc_uz: "CSS, JavaScript va HTML5 texnologiyalarining barcha zamonaviy brauzerlarda qo'llab-quvvatlanish jadvali.",
        snippet: 'https://caniuse.com',
        tag: 'Frontend',
        tag_uz: 'Frontend',
        type: 'tool',
      },
      {
        id: '7',
        title: 'DevDocs.io: Быстрая документация оффлайн',
        title_uz: 'DevDocs.io: Barcha hujjatlar bitta joyda',
        url: 'https://devdocs.io',
        desc: 'Единый оффлайн-справочник документации по десяткам языков и фреймворков с мгновенным поиском.',
        desc_uz: "React, Node, CSS, PostgreSQL kabi o'nlab texnologiyalarning rasmiy hujjatlari bitta qulay qidiruvda.",
        snippet: 'https://devdocs.io',
        tag: 'Docs',
        tag_uz: 'Hujjat',
        type: 'tool',
      },
      {
        id: '8',
        title: 'QuickType: Генератор TypeScript типов из JSON',
        title_uz: 'QuickType: JSON-dan TypeScript turlarini yaratish',
        url: 'https://quicktype.io',
        desc: 'Мгновенная генерация строгих типов TypeScript, Go structs и кодовых моделей из примера JSON ответа API.',
        desc_uz: "API-dan qaytgan JSON namunasi asosida TypeScript interfeyslari yoki Go turlarini bir zumda yaratish.",
        snippet: 'https://quicktype.io',
        tag: 'TypeScript',
        tag_uz: 'TypeScript',
        type: 'tool',
      },
      {
        id: '9',
        title: 'Diffchecker: Сравнение текста и кода онлайн',
        title_uz: 'Diffchecker: Kod va matnlarni solishtirish',
        url: 'https://diffchecker.com',
        desc: 'Визуальное сравнение двух версий текста, конфигов или кода с подсветкой различий по строкам и символам.',
        desc_uz: "Ikkita matn yoki konfiguratsiya fayli orasidagi farqlarni rangli qatorlar bilan solishtirish.",
        snippet: 'https://diffchecker.com',
        tag: 'Tools',
        tag_uz: 'Vosita',
        type: 'tool',
      },
      {
        id: '10',
        title: 'SVGOMG: Оптимизация и сжатие SVG иконок',
        title_uz: 'SVGOMG: SVG fayllarni siqish va tozalash',
        url: 'https://jakearchibald.github.io/svgomg',
        desc: 'Веб-оптимизатор SVG: удаляет лишние метаданные редакторов Figma/Illustrator без потери визуального качества.',
        desc_uz: "SVG ikonkalar hajmini keraksiz teglarni tozalash orqali sifatini buzmasdan 60% gacha kichraytirish.",
        snippet: 'https://jakearchibald.github.io/svgomg',
        tag: 'Frontend',
        tag_uz: 'Frontend',
        type: 'tool',
      },
      {
        id: '11',
        title: 'CyberChef: Швейцарский нож для декодирования',
        title_uz: 'CyberChef: Shifrlash va dekodlash vositasi',
        url: 'https://gchq.github.io/CyberChef',
        desc: 'Швейцарский нож разработчика: кодирование Base64, Hex, парсинг JWT токенов, вычисление хэшей SHA/MD5.',
        desc_uz: "Base64, Hex, URL-kodlash, JWT tokenlarni o'qish va xeshlar bilan ishlash uchun professional laboratoriya.",
        snippet: 'https://gchq.github.io/CyberChef',
        tag: 'Security',
        tag_uz: 'Xavfsizlik',
        type: 'tool',
      },
      {
        id: '12',
        title: 'SQL Murder Mystery: Игра-расследование на SQL',
        title_uz: 'SQL Murder Mystery: SQL o\'yini',
        url: 'https://mystery.knightlab.com',
        desc: 'Обучающая детективная игра для оттачивания реальных навыков SQL: поиск улик через JOIN, WHERE и GROUP BY.',
        desc_uz: "JOIN, WHERE va GROUP BY buyruqlarini qiziqarli detektiv tergov orqali o'rganish amaliyoti.",
        snippet: 'https://mystery.knightlab.com',
        tag: 'Practice',
        tag_uz: 'Amaliyot',
        type: 'tool',
      },
    ]
  },
  news: {
    title: 'Новости & Тренды',
    title_uz: 'IT Yangiliklari',
    subtitle: 'React 19, AI, Highload',
    subtitle_uz: 'React 19, AI, Highload',
    desc: 'Актуальные IT-новости, релизы технологий, тренды AI и дайджесты индустрии',
    desc_uz: 'Eng so\'nggi IT yangiliklari, yangi relizlar, AI trendlari va texnologiya dayjestlari',
    color: '#06B6D4',
    icon: 'radio',
    badge: 'TRENDS',
    extra: 'Тренды & Релизы',
    extra_uz: 'Trendlar & Relizlar',
    items: [
      {
        id: '1',
        title: 'React 19 и Next.js 15: Главные архитектурные фичи',
        title_uz: 'React 19 va Next.js 15: Asosiy arxitektura yangiliklari',
        desc: '• Server Components по умолчанию без директивы "use client"\n• Новые хуки: useActionState, useFormStatus, useOptimistic\n• Server Actions для прямой работы с БД без API роутов\n• Turbopack стал стабильным и быстрее Webpack в 3-5 раз.',
        desc_uz: "• Server Components standart bo'yicha\n• Yangi hooklar: useActionState, useOptimistic\n• Server Actions orqali to'g'ridan-to'g'ri MB bilan ishlash\n• Turbopack barqarorlashdi va Webpack-dan 3-5 marta tezroq.",
        url: 'https://react.dev/blog/2024/12/05/react-19',
        snippet: 'React 19 & Next.js 15',
        tag: 'Frontend',
        tag_uz: 'Frontend',
        type: 'news',
      },
      {
        id: '2',
        title: 'AI-агенты и кодинг: Эра Cursor, Claude 3.5 & Copilot Workspace',
        title_uz: 'AI-agentlar va dasturlash: Cursor, Claude 3.5 va Copilot Workspace',
        desc: 'Переход от простых строчных автодополнений к автономным AI-агентам: мультифайловый рефакторинг, автогенерация тестов, глубокий контекст всего репозитория и фоновые CLI-агенты.',
        desc_uz: "Oddiy avtoto'ldirishdan to'liq avtonom AI-agentlarga o'tish: butun loyiha bo'ylab refaktoring, testlar yozish va buyruqlar bajarish.",
        snippet: 'AI Agents in Software Engineering',
        tag: 'AI',
        tag_uz: 'AI',
        type: 'news',
      },
      {
        id: '3',
        title: 'Node.js 22 LTS: Нативный TypeScript без компиляции',
        title_uz: 'Node.js 22 LTS: TypeScript-ni kompilyatsiyasiz to\'g\'ridan-to\'g\'ri ishga tushirish',
        desc: 'Флаг node --experimental-strip-types позволяет напрямую запускать .ts файлы без ts-node или предварительной сборки tsc. Также: нативный WebSocket клиент и ускоренный движок V8 12.4.',
        desc_uz: "node --experimental-strip-types bayrog'i .ts fayllarni ts-node yoki tsc-siz to'g'ridan-to'g'ri ishga tushirish imkonini beradi. Shuningdek: native WebSocket va tezkor V8.",
        url: 'https://nodejs.org/en/blog/release/v22.0.0',
        snippet: 'Node.js 22 LTS Release',
        tag: 'Node.js',
        tag_uz: 'Node.js',
        type: 'news',
      },
      {
        id: '4',
        title: 'TypeScript 5.5+: Инференс предикатов типов и isolatedDeclarations',
        title_uz: 'TypeScript 5.5+: Type Predicates avtomatik aniqlanishi',
        desc: 'Фильтрация массивов (arr.filter(x => x !== null)) теперь автоматически сужает типы без ручного "x is Type". Опция isolatedDeclarations ускоряет параллельный тайпчекинг монорепозиториев.',
        desc_uz: "Massivlarni filtrlashda (arr.filter(x => x !== null)) endi turlar avtomatik torayadi. isolatedDeclarations esa katta loyihalarda tezlikni oshiradi.",
        url: 'https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/',
        snippet: 'TypeScript 5.5+ Release',
        tag: 'TypeScript',
        tag_uz: 'TypeScript',
        type: 'news',
      },
      {
        id: '5',
        title: 'PostgreSQL 17: Новые возможности памяти и JSON',
        title_uz: 'PostgreSQL 17: Xotira optimizatsiyasi va yangi JSON imkoniyatlari',
        desc: '• Потребление памяти процессом VACUUM снижено до 2 раз\n• Добавлен стандартный конструктор JSON_TABLE() для преобразования JSON в реляционные строки\n• Улучшена производительность логической репликации и экспорта.',
        desc_uz: "• VACUUM jarayonining RAM sarfi 2 martagacha kamaytirildi\n• Standart JSON_TABLE() funksiyasi qo'shildi\n• Replikatsiya va parallel eksport tezligi sezilarli oshirildi.",
        url: 'https://www.postgresql.org/about/news/postgresql-17-released-2936/',
        snippet: 'PostgreSQL 17 Release Notes',
        tag: 'Database',
        tag_uz: 'MB',
        type: 'news',
      },
      {
        id: '6',
        title: 'Hacker News: Главный пульс мирового IT сообщества',
        title_uz: 'Hacker News: Dunyo IT hamjamiyatining bosh axborot manbasi',
        desc: 'Ежедневные инсайды от основателей стартапов, новости Кремниевой долины, глубокие обсуждения архитектуры распределенных систем и свежие релизы открытого ПО.',
        desc_uz: "Silikon vodiysi startapchilari, dasturlash yangiliklari, arxitektura muhokamalari va eng yangi Open Source loyihalar jamlangan platforma.",
        url: 'https://news.ycombinator.com',
        snippet: 'https://news.ycombinator.com',
        tag: 'Новости',
        tag_uz: 'Yangilik',
        type: 'news',
      },
      {
        id: '7',
        title: 'Habr Highload: Разборы реальных аварий и архитектуры',
        title_uz: 'Habr Highload: Yuqori yuklama va arxitektura tahlillari',
        desc: 'Еженедельные инженерные лонгриды: как сервисы выдерживают миллионы RPS, тюнинг Postgres и Nginx под высокие нагрузки, разборы постмортемов реальных аварий.',
        desc_uz: "Millionlab RPS yuklamalar, Nginx/Postgres sozlamalari va yirik tizimlar arxitekturasi bo'yicha batafsil muhandislik maqolalari.",
        url: 'https://habr.com/ru/flows/develop/',
        snippet: 'https://habr.com/ru/flows/develop/',
        tag: 'Дайджест',
        tag_uz: 'Dayjest',
        type: 'news',
      },
      {
        id: '8',
        title: 'Миграция сообщества: OpenTofu вместо закрытого Terraform',
        title_uz: 'Hamjamiyat tanlovi: Yopiq Terraform o\'rniga ochiq OpenTofu',
        desc: 'После изменения лицензии HashiCorp сообщество под эгидой Linux Foundation создало независимый форк OpenTofu: полная обратная совместимость, 100% open-source и поддержка всех провайдеров.',
        desc_uz: "HashiCorp litsenziya siyosatini o'zgartirgach, Linux Foundation homiyligida OpenTofu yaratildi: to'liq moslik va 100% ochiq kodli infratuzilma.",
        url: 'https://opentofu.org',
        snippet: 'https://opentofu.org',
        tag: 'DevOps',
        tag_uz: 'DevOps',
        type: 'news',
      },
      {
        id: '9',
        title: 'Безопасность Supply Chain: Атаки на NPM и реестры пакетов',
        title_uz: 'Dasturiy xavfsizlik: NPM va paketlar omboriga uyushtirilgan hujumlar',
        desc: 'Рост случаев Typosquatting и атак на пакеты. Защита: жесткая фиксация версий в package-lock.json, запуск npm audit в CI/CD пайплайнах, включение 2FA и сканирование через Trivy/Snyk.',
        desc_uz: "NPM paketlariga kiberhujumlar ko'paymoqda. Himoya: lockfile versiyalarini qat'iy saqlash, CI-da npm audit o'tkazish va 2FA-ni yoqish shart.",
        snippet: 'Software Supply Chain Security',
        tag: 'Security',
        tag_uz: 'Xavfsizlik',
        type: 'news',
      },
      {
        id: '10',
        title: 'O\'zbekiston IT ekotizimi: IT Park, IT Community & Mohirdev',
        title_uz: 'O\'zbekiston IT ekotizimi: IT Park, Hamjamiyat va Yangiliklar',
        desc: 'O\'zbekistonda IT sohasining jadal rivojlanishi: IT Park rezidentlari uchun soliq imtiyozlari, yangi BPO/R&D markazlari, kiberxavfsizlik qonunchiligi va startap grantlari.',
        desc_uz: "O'zbekiston IT bozori yangiliklari: soliq imtiyozlari, xalqaro frilans, startaplar va mahalliy dasturchilar uchun ta'lim grantlari.",
        url: 'https://it-park.uz',
        snippet: 'https://it-park.uz',
        tag: 'Ekotizim',
        tag_uz: 'Ekotizim',
        type: 'news',
      },
      {
        id: '11',
        title: 'GitHub Trending: Радар трендовых Open Source репозиториев',
        title_uz: 'GitHub Trending: Ochiq kodli loyihalar radari',
        desc: 'Ежедневно обновляемый срез самых популярных проектов на GitHub: новые LLM-фреймворки, легковесные базы данных, полезные инструменты и крутые открытые библиотеки.',
        desc_uz: "Dunyo dasturchilari orasida ayni damda eng ommalashayotgan yangi kutubxonalar, vositalar va sun'iy intellekt freymvorklari.",
        url: 'https://github.com/trending',
        snippet: 'https://github.com/trending',
        tag: 'OpenSource',
        tag_uz: 'OpenSource',
        type: 'news',
      },
      {
        id: '12',
        title: 'BleepingComputer & CVE: Главный мониторинг киберугроз',
        title_uz: 'BleepingComputer & CVE: Kiberxavflar va 0-day zaifliklar monitoringi',
        desc: 'Оперативные публикации о свежих критических 0-day уязвимостях в ядре Linux, браузерах, Nginx и облачных платформах AWS / GCP.',
        desc_uz: "Linux yadrosi, brauzerlar, Nginx va bulutli tizimlardagi yangi 0-day xatoliklar va xavfsizlik yangilanishlari.",
        url: 'https://bleepingcomputer.com',
        snippet: 'https://bleepingcomputer.com',
        tag: 'Security',
        tag_uz: 'Xavfsizlik',
        type: 'news',
      },
    ]
  }
};
