export const OPEN_MEDIA_RESOURCES = [
  {
    id: 'm1',
    category: 'course',
    platform: 'Harvard / edX',
    platform_icon: 'award',
    duration: '24+ ч (12 лекций)',
    duration_uz: '24+ soat (12 dars)',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'Гарвардский курс CS50: Основы Computer Science',
    title_uz: 'Garvard CS50: Computer Science asoslari',
    desc: 'Легендарный открытый курс по алгоритмам, памяти C, структурам данных, Python, SQL и веб-технологиям от профессора Дэвида Малана.',
    desc_uz: 'Algoritmlar, xotira, C, Python, SQL va kompyuter fanlari asoslari bo\'yicha Garvard universitetining afsonaviy ochiq kursi.',
    url: 'https://www.youtube.com/watch?v=8mAITcNt710',
  },
  {
    id: 'm2',
    category: 'course',
    platform: 'Helsinki Uni',
    platform_icon: 'book',
    duration: '13 частей',
    duration_uz: '13 ta qism',
    langCode: 'ru_en',
    langBadge: 'RU & EN',
    langBadge_uz: 'RU & EN',
    title: 'Full Stack Open: React, Redux, Node.js & TypeScript',
    title_uz: 'Full Stack Open: React, Node.js va TypeScript kursi',
    desc: 'Официальный открытый курс университета Хельсинки: React, Node.js, Express, MongoDB, GraphQL, TypeScript, Docker и CI/CD.',
    desc_uz: 'Xelsinki universitetining zamonaviy veb-ishlab chiqish bo\'yicha to\'liq ochiq kursi: React, Node.js, GraphQL va Docker.',
    url: 'https://fullstackopen.com/en/',
  },
  {
    id: 'm3',
    category: 'course',
    platform: 'YouTube (Sammi)',
    platform_icon: 'play-circle',
    duration: '12+ соат',
    duration_uz: '12+ soat',
    langCode: 'uz',
    langBadge: 'O\'zbekcha',
    langBadge_uz: 'O\'zbekcha',
    title: 'Sammi: Frontend & JavaScript darslari (O\'zbek tilida)',
    title_uz: 'Sammi: Frontend & JavaScript darslari',
    desc: 'O\'zbek tilidagi eng sifatli video kurs: JavaScript asoslari, DOM, loyihalar va zamonaviy veb amaliyoti.',
    desc_uz: 'JavaScript asoslari, DOM bilan ishlash, funksiyalar va amaliy loyihalar bo\'yicha o\'zbek tilidagi to\'liq video kurs.',
    url: 'https://www.youtube.com/@samarbadriddinov',
  },
  {
    id: 'm4',
    category: 'video',
    platform: 'YouTube (Ulbi TV)',
    platform_icon: 'cpu',
    duration: '30-60 мин',
    duration_uz: '30-60 daqiqa',
    langCode: 'ru',
    langBadge: 'Русский',
    langBadge_uz: 'Ruscha',
    title: 'Ulbi TV: Архитектура, React, TypeScript & Микросервисы',
    title_uz: 'Ulbi TV: Arxitektura, React va mikroxizmatlar',
    desc: 'Глубокие русскоязычные видеоразборы: Clean Architecture, паттерны проектирования, Event Loop, TypeScript, WebSockets и производительность.',
    desc_uz: 'Clean Architecture, loyihalash andozalari, Event Loop va mikroxizmatlar bo\'yicha rus tilidagi chuqur amaliy tahlillar.',
    url: 'https://www.youtube.com/@UlbiTV',
  },
  {
    id: 'm5',
    category: 'course',
    platform: 'YouTube (Минин)',
    platform_icon: 'award',
    duration: '6 ч',
    duration_uz: '6 soat',
    langCode: 'ru',
    langBadge: 'Русский',
    langBadge_uz: 'Ruscha',
    title: 'Владилен Минин: JavaScript с нуля до профи (6 часов)',
    title_uz: 'Vladilen Minin: JavaScript noldan to\'liq kurs (6 soat)',
    desc: 'Фундаментальный 6-часовой курс: замыкания, прототипы, асинхронность, промисы, классы и современные методы ES6+.',
    desc_uz: 'JavaScript asoslari, yopilishlar (closures), prototiplar va asinxronlik bo\'yicha mashhur 6 soatlik rus tilidagi kurs.',
    url: 'https://www.youtube.com/watch?v=Bluxbh9CaQ0',
  },
  {
    id: 'm6',
    category: 'video',
    platform: 'YouTube (Kadirov)',
    platform_icon: 'server',
    duration: '20-40 мин',
    duration_uz: '20-40 daqiqa',
    langCode: 'uz',
    langBadge: 'O\'zbekcha',
    langBadge_uz: 'O\'zbekcha',
    title: 'Kadirov Dev: Backend & Server darslari (O\'zbekcha)',
    title_uz: 'Kadirov Dev: Backend & Server darslari',
    desc: 'O\'zbek tilida backend arxitekturasi, ma\'lumotlar bazasi, REST API va serverlarni boshqarish darslari.',
    desc_uz: 'O\'zbek tilida backend arxitekturasi, ma\'lumotlar bazasi, REST API va serverlarni boshqarish darslari.',
    url: 'https://www.youtube.com/@kadirovdev',
  },
  {
    id: 'm7',
    category: 'video',
    platform: 'YouTube (Fireship)',
    platform_icon: 'zap',
    duration: '2-5 мин / серия',
    duration_uz: '2-5 daqiqa / qism',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'Fireship: Технологии и базы данных за 100 секунд',
    title_uz: 'Fireship: Texnologiyalar va MB-lar 100 soniyada',
    desc: 'Молниеносные, наглядные видеоразборы концепций: SQL vs NoSQL, Docker, Git, WebSockets, Rust, Redis и тренды IT.',
    desc_uz: 'SQL vs NoSQL, Docker, Git, WebSockets va dasturlash trendlari bo\'yicha eng tezkor va qiziqarli vizual darslar.',
    url: 'https://www.youtube.com/@Fireship',
  },
  {
    id: 'm8',
    category: 'course',
    platform: 'freeCodeCamp',
    platform_icon: 'play-circle',
    duration: '8 ч 15 мин',
    duration_uz: '8 soat 15 daqiqa',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'Полный видеокурс по Node.js & Express API',
    title_uz: 'Node.js va Express API to\'liq video kursi',
    desc: 'Фундаментальный видеокурс: Event Loop, Streams, REST API, Express Middleware, аутентификация JWT и работа с БД.',
    desc_uz: 'Node.js arxitekturasi, Event Loop, REST API, middleware, JWT tokenlar va ma\'lumotlar bazasi bo\'yicha amaliy dars.',
    url: 'https://www.youtube.com/watch?v=Oe421EPjeBE',
  },
  {
    id: 'm9',
    category: 'video',
    platform: 'YouTube (Hussein Nasser)',
    platform_icon: 'server',
    duration: '15-30 мин',
    duration_uz: '15-30 daqiqa',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'Глубокий бэкенд: TCP, HTTP/3, Postgres & Протоколы',
    title_uz: 'Chuqur bekend: TCP, HTTP/3, Postgres va tarmoqlar',
    desc: 'Глубокие инженерные видеокасты: устройство пулинга соединений, внутренности PostgreSQL, HTTP/1 vs HTTP/2 vs HTTP/3, TLS.',
    desc_uz: 'PostgreSQL ichki tuzilishi, connection pooling, HTTP/1 vs HTTP/2 vs HTTP/3, TCP protokoli va tarmoq muhandisligi tahlili.',
    url: 'https://www.youtube.com/@hnasr',
  },
  {
    id: 'm10',
    category: 'video',
    platform: 'YouTube (ByteByteGo)',
    platform_icon: 'layout',
    duration: '8-15 мин',
    duration_uz: '8-15 daqiqa',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'ByteByteGo: Анимации архитектуры System Design',
    title_uz: 'ByteByteGo: Tizim dizayni va arxitektura animatsiyalari',
    desc: 'Наглядные схемы и разборы масштабирования: кэш Redis, брокеры Kafka, шардирование БД, Rate Limiter и CDN.',
    desc_uz: 'Redis kesh, Kafka navbatlari, bazani shardlash, Rate Limiter va CDN ishlash tamoyillarini animatsiyalarda tushuntirish.',
    url: 'https://www.youtube.com/@ByteByteGo',
  },
  {
    id: 'm11',
    category: 'video',
    platform: 'YouTube (ThePrimeagen)',
    platform_icon: 'cpu',
    duration: '20-45 мин',
    duration_uz: '20-45 daqiqa',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'ThePrimeagen: Архитектура, Vim, Go и факапы в IT',
    title_uz: 'ThePrimeagen: Arxitektura, tezkor dasturlash va xatolar',
    desc: 'Опытный инженер из Netflix разбирает реальные архитектуры, аллокацию памяти, производительность и новости индустрии.',
    desc_uz: 'Netflix sobiq muhandisi tomonidan tizim arxitekturasi, xotira optimallashtirish va IT dunyosidagi muhim yangiliklar tahlili.',
    url: 'https://www.youtube.com/@ThePrimeTimeagen',
  },
  {
    id: 'm12',
    category: 'video',
    platform: 'YouTube (NeetCode)',
    platform_icon: 'code',
    duration: '10-20 мин',
    duration_uz: '10-20 daqiqa',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'NeetCode: Пошаговые разборы алгоритмов и структур',
    title_uz: 'NeetCode: Algoritmlar va LeetCode masalalari tahlili',
    desc: 'Лучшие видеоразборы алгоритмических паттернов: Sliding Window, Двухуказатели, Деревья, Графы, Динамическое программирование.',
    desc_uz: 'Katta kompaniyalar intervyusi uchun algoritmlar: ikkita ko\'rsatkich, sliding window, daraxtlar, graflar va dinamik dasturlash.',
    url: 'https://www.youtube.com/@NeetCode',
  },
  {
    id: 'm13',
    category: 'course',
    platform: 'MIT OpenCourseWare',
    platform_icon: 'award',
    duration: '24 лекции',
    duration_uz: '24 ta ma\'ruza',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'MIT 6.006: Введение в алгоритмы (Лекции MIT)',
    title_uz: 'MIT 6.006: Algoritmlarga kirish (MIT ma\'ruzalari)',
    desc: 'Официальные видеолекции профессоров MIT по анализу сложности алгоритмов, хеш-таблицам, деревьям поиска и графам.',
    desc_uz: 'Massachusets Texnologiya Instituti (MIT) professorlarining algoritmlar va ma\'lumotlar tuzilmalari bo\'yicha rasmiy video kursi.',
    url: 'https://www.youtube.com/playlist?list=PLUl4u3cNGP61Oq3tWYp6V_F-5jb5L2iHb',
  },
  {
    id: 'm14',
    category: 'podcast',
    platform: 'Syntax.fm',
    platform_icon: 'headphones',
    duration: '45-60 мин',
    duration_uz: '45-60 daqiqa',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'Syntax.fm: Подкаст о Fullstack, React и Node.js',
    title_uz: 'Syntax.fm: Fullstack, React va Node.js haqida podkast',
    desc: 'Wes Bos и Scott Tolinski еженедельно обсуждают новые фичи JavaScript, React 19, CSS, хостинг, TypeScript и производительность.',
    desc_uz: 'Wes Bos va Scott Tolinski har hafta JavaScript, React 19, TypeScript, serverlar va yangi veb-vositalarni muhokama qilishadi.',
    url: 'https://syntax.fm',
  },
  {
    id: 'm15',
    category: 'course',
    platform: 'freeCodeCamp',
    platform_icon: 'box',
    duration: '4 ч',
    duration_uz: '4 soat',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'Docker и контейнеры с нуля до деплоя',
    title_uz: 'Docker va konteynerlar noldan deploygacha',
    desc: 'Практический видеокурс: сборка Dockerfile, Docker Compose, монтирование томов, сети и основы запуска в Kubernetes.',
    desc_uz: 'Dockerfile yozish, Docker Compose, tarmoqlar, hajmlar (volumes) va Kubernetes asoslari bo\'yicha qulay video darslik.',
    url: 'https://www.youtube.com/watch?v=fqMOX6JJhGo',
  },
  {
    id: 'm16',
    category: 'podcast',
    platform: 'YouTube (АйТиБорода)',
    platform_icon: 'mic',
    duration: '1-2 ч',
    duration_uz: '1-2 soat',
    langCode: 'ru',
    langBadge: 'Русский',
    langBadge_uz: 'Ruscha',
    title: 'АйТиБорода: Большие интервью с инженерами и CTO',
    title_uz: 'ITBeard: Yetakchi dasturchilar va CTO bilan suhbatlar',
    desc: 'Интервью с ведущими инженерами, архитекторами и фаундерами: карьера, архитектура систем, фреймворки и инсайды индустрии.',
    desc_uz: 'Yirik tizimlar arxitektorlari, muhandislar va startap asoschilari bilan chuqur kasbiy intervyular.',
    url: 'https://www.youtube.com/@itbeard',
  },
  {
    id: 'm17',
    category: 'news',
    platform: 'Hacker News / YC',
    platform_icon: 'trending-up',
    duration: 'Ежедневно',
    duration_uz: 'Har kuni',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'Hacker News: Главный источник IT-новостей кремниевой долины',
    title_uz: 'Hacker News: Silikon vodiysining eng sara IT yangiliklari',
    desc: 'Самый авторитетный ресурс мирового IT-сообщества: запуски Open Source проектов, обсуждения архитектуры, безопасности и AI.',
    desc_uz: 'Dunyodagi eng nufuzli IT hamjamiyatining muhokamalari: Open Source loyihalar, arxitektura, xavfsizlik va AI yangiliklari.',
    url: 'https://news.ycombinator.com/',
  },
  {
    id: 'm18',
    category: 'news',
    platform: 'Habr.com',
    platform_icon: 'file-text',
    duration: 'Статьи',
    duration_uz: 'Maqolalar',
    langCode: 'ru',
    langBadge: 'Русский',
    langBadge_uz: 'Ruscha',
    title: 'Хабр: Отборные статьи по разработке и бэкенду',
    title_uz: 'Habr: Dasturlash va bekend bo\'yicha saralangan maqolalar',
    desc: 'Русскоязычные лонгриды и практический опыт: архитектура высоконагруженных сервисов, разборы багов, репликация PostgreSQL.',
    desc_uz: 'Yuqori yuklamali tizimlar, xatoliklarni bartaraf etish, PostgreSQL replikatsiyasi va mikroxizmatlar bo\'yicha chuqur maqolalar.',
    url: 'https://habr.com/ru/articles/',
  },
  {
    id: 'm19',
    category: 'news',
    platform: 'roadmap.sh',
    platform_icon: 'map',
    duration: 'Интерактив',
    duration_uz: 'Interaktiv',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'roadmap.sh: Детальные роадмапы для разработчиков',
    title_uz: 'roadmap.sh: Dasturchilar uchun interaktiv yo\'l xaritalari',
    desc: 'Сообщество номер один по картам развития: Frontend, Backend, DevOps, PostgreSQL, Docker, System Design и Cybersecurity.',
    desc_uz: 'Frontend, Backend, DevOps, PostgreSQL, Docker va System Design yo\'nalishlarida o\'rganish bo\'yicha eng mashhur xaritalar.',
    url: 'https://roadmap.sh',
  },
  {
    id: 'm20',
    category: 'course',
    platform: 'pgexercises.com',
    platform_icon: 'terminal',
    duration: 'Практика',
    duration_uz: 'Amaliyot',
    langCode: 'en',
    langBadge: 'English',
    langBadge_uz: 'Inglizcha',
    title: 'PGExercises: Интерактивные задачи по SQL и Postgres',
    title_uz: 'PGExercises: SQL va Postgres bo\'yicha interaktiv mashqlar',
    desc: 'Бесплатный интерактивный тренажер: JOIN, агрегации, оконные функции (Window Functions), CTE и рекурсивные запросы в PostgreSQL.',
    desc_uz: 'Haqiqiy ma\'lumotlar bazasida bepul mashqlar: JOIN, agregatsiya, oynali funksiyalar (Window Functions) va CTE so\'rovlari.',
    url: 'https://pgexercises.com/',
  },
];
